---
apiVersion: v1
kind: Service
metadata:
  name: ak-ldap-outpost
  namespace: authentik
spec:
  type: ClusterIP
  selector:
    app: ak-ldap-outpost
  ports:
    - name: ldap
      port: 389
      targetPort: 3389
      protocol: TCP
    - name: ldaps
      port: 636
      targetPort: 6636
      protocol: TCP
