apiVersion: v1
kind: Secret
metadata:
  name: pastefy-db-secret
  namespace: pastefy
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: UkVQTEFDRV9NRQ==
  MYSQL_DATABASE: UkVQTEFDRV9NRQ==
  MYSQL_USER: UkVQTEFDRV9NRQ==
  MYSQL_PASSWORD: UkVQTEFDRV9NRQ==

# =====================================
# 2. StorageClass (Ceph)
# =====================================

# =====================================
# 3. Headless Service (StatefulSet DNS)
# =====================================
