
# =====================================
# Service (ClusterIP) - 80 -> 8080
# =====================================
---
apiVersion: v1
kind: Service
metadata:
  name: renovate
  namespace: renovate
spec:
  type: ClusterIP
  selector:
    app: renovate
  ports:
    - name: http
      port: 80          # external in-cluster port
      targetPort: 8080  # containerPort
