apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-exporter-certs
  namespace: pihole-exporter
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
