apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - semaphore-app-service.yml
  - semaphore-db-init-configmap.yml
  - semaphore-db-service.yml
  - semaphore-db-statefulset.yml
  - semaphore-ingress.yml
  - semaphore-namespace.yml
  - semaphore-secret.yml
  - semaphore-statefulset.yml
