services:
  wallos:
    image: bellamy/wallos:5.4.5
    environment:
      TZ: ${WALLOS_TZ}
    ports:
      - "80:80/tcp"
    volumes:
      - './db:/var/www/html/db'
      - './logos:/var/www/html/images/uploads/logos'


