apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-config
  namespace: blackbox
data:
  blackbox.yml: |
    modules:
      http_minimal:
        prober: http
        timeout: 10s
        http:
          method: GET
          follow_redirects: true
          preferred_ip_protocol: "ip4"
          enable_http2: true

      http_insecure:
        prober: http
        timeout: 10s
        http:
          method: GET
          follow_redirects: true
          preferred_ip_protocol: "ip4"
          enable_http2: true
          tls_config:
            insecure_skip_verify: true

      icmp:
        prober: icmp
        timeout: 3s
        icmp:
          preferred_ip_protocol: "ip4"

      tls_connect:
        prober: tcp
        timeout: 10s
        tcp:
          tls: true
          tls_config:
            insecure_skip_verify: true
          preferred_ip_protocol: "ip4"
