apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy-manager
  namespace: nginx-proxy-manager
  labels:
    app: nginx-proxy-manager
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx-proxy-manager
  template:
    metadata:
      labels:
        app: nginx-proxy-manager
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      containers:
        - name: nginx-proxy-manager
          image: jc21/nginx-proxy-manager:2.13.6
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
            - name: webui
              containerPort: 81
            - name: https
              containerPort: 443
          env:
            - name: DB_MYSQL_HOST
              value: "mariadb"
            - name: DB_MYSQL_PORT
              value: "3306"
            - name: DB_MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MYSQL_USER
            - name: DB_MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: DB_MYSQL_PASSWORD
            - name: DB_MYSQL_NAME
              value: "proxy-manager"
          volumeMounts:
            - name: data
              mountPath: /data
            - name: letsencrypt
              mountPath: /etc/letsencrypt
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /admin/api/healthcheck
              port: 81
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /admin/api/healthcheck
              port: 81
            initialDelaySeconds: 30
            periodSeconds: 15
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: npm-data-pvc
        - name: letsencrypt
          persistentVolumeClaim:
            claimName: npm-letsencrypt-pvc
