apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: nginx-proxy-manager
  labels:
    app: mariadb
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "REPLACE_ME"
  MYSQL_USER: "REPLACE_ME"
  MYSQL_PASSWORD: "REPLACE_ME"
  DB_MYSQL_PASSWORD: "REPLACE_ME"
