apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallos-logos-pvc
  namespace: wallos
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi

