apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallos-db-pvc
  namespace: wallos
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
