apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zabbix-snmptraps-data
  namespace: zabbix
spec:
  storageClassName: longhorn
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
