[global]
	auth_client_required = cephx
	auth_cluster_required = cephx
	auth_service_required = cephx
	public_network = 192.0.2.0/24
	cluster_network = 198.51.100.0/24
	fsid = 00000000-0000-4000-8000-000000000000
	mon_allow_pool_delete = true
	mon_host = 192.0.2.11 192.0.2.13 192.0.2.12
	ms_bind_ipv4 = true
	ms_bind_ipv6 = false
	osd_pool_default_min_size = 2
	osd_pool_default_size = 3
	osd_memory_target = 6442450944
	mds_cache_memory_limit = 6442450944
	osd_recovery_max_active = 1
	osd_max_backfills = 1
	osd_recovery_op_priority = 1
	bluestore_warn_on_slow_ops_threshold = 20

[client]
	keyring = /etc/pve/priv/$cluster.$name.keyring

[client.crash]
	keyring = /etc/pve/ceph/$cluster.$name.keyring

[mds]
	keyring = /var/lib/ceph/mds/ceph-$id/keyring

[mds.pve-node01]
	host = pve-node01
	mds_standby_for_name = pve

[mds.pve-node02]
	host = pve-node02
	mds_standby_for_name = pve

[mds.pve-node03]
	host = pve-node03
	mds_standby_for_name = pve

[mon.pve-node01]
	public_addr = 192.0.2.11

[mon.pve-node02]
	public_addr = 192.0.2.12

[mon.pve-node03]
	public_addr = 192.0.2.13

