apiVersion: v1
kind: Service
metadata:
  name: portainer
  namespace: portainer
  labels:
    app: portainer
spec:
  type: ClusterIP
  selector:
    app: portainer
  ports:
  - name: edge
    protocol: TCP
    port: 8000
    targetPort: 8000
  - name: https
    protocol: TCP
    port: 9443
    targetPort: 9443

