apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer
  namespace: portainer
  labels:
    app: portainer
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: portainer
  template:
    metadata:
      labels:
        app: portainer
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      containers:
      - name: portainer
        image: portainer/portainer-ce:2.39.1
        imagePullPolicy: IfNotPresent
        ports:
        - name: edge
          containerPort: 8000
        - name: https
          containerPort: 9443
        volumeMounts:
        - name: data
          mountPath: /data
        readinessProbe:
          tcpSocket:
            port: 9443
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 9443
          initialDelaySeconds: 30
          periodSeconds: 15
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: portainer-data-pvc

