apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gitlab-runner-admin-binding-clusterrolebinding.yml
  - gitlab-runner-config-configmap.yml
  - gitlab-runner-deployment.yml
  - gitlab-runner-namespace.yml
  - gitlab-runner-pvc-persistentvolumeclaim.yml
  - gitlab-runner-secret.yml
  - gitlab-runner-sa-serviceaccount.yml
