apiVersion: v1
kind: Secret
metadata:
  name: affine-secrets
  namespace: affine
type: Opaque
stringData:
  DB_USERNAME: "REPLACE_ME"
  DB_PASSWORD: "REPLACE_ME"
  DB_DATABASE: "REPLACE_ME"

  REDIS_PASSWORD: "REPLACE_ME"

  AFFINE_INDEXER_ENABLED: "REPLACE_ME"
  AFFINE_SERVER_EXTERNAL_URL: "REPLACE_ME"

  DATABASE_URL: "REPLACE_ME"

