---
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-db-secret
  namespace: vaultwarden
  labels:
    app: vaultwarden-db
type: Opaque
data:
  POSTGRES_DB: UkVQTEFDRV9NRQ==
  POSTGRES_USER: "REPLACE_ME"
  POSTGRES_PASSWORD: "REPLACE_ME"
---
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
  namespace: vaultwarden
  labels:
    app: vaultwarden
type: Opaque
data:
  DATABASE_URL: UkVQTEFDRV9NRQ==
