---
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-db-secret
  namespace: vaultwarden
  labels:
    app: vaultwarden-db
type: Opaque
stringData:
  POSTGRES_DB: "REPLACE_ME"
  POSTGRES_USER: "REPLACE_ME"
  POSTGRES_PASSWORD: "REPLACE_ME"
---
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
  namespace: vaultwarden
  labels:
    app: vaultwarden
type: Opaque
stringData:
  DATABASE_URL: "postgresql://REPLACE_ME:REPLACE_ME@vaultwarden-db:5432/REPLACE_ME"
