apiVersion: v1
kind: Secret
metadata:
  name: affine-secrets
  namespace: affine
type: Opaque
stringData:
  DB_USERNAME: "REPLACE_ME"
  DB_PASSWORD: "REPLACE_ME"
  DB_DATABASE: "affine"

  REDIS_PASSWORD: "REPLACE_ME"

  AFFINE_INDEXER_ENABLED: "false"
  AFFINE_SERVER_EXTERNAL_URL: "https://affine.example.com"

  DATABASE_URL: "REPLACE_ME"

