global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "node-exporter-rules.yml"
  - "kubernetes-rules.yml"
  - "prometheus-self-monitoring-rules.yml"
  - "longhorn-rules.yml"
  - "pve-exporter-rules.yml"
  - "blackbox-rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager.alertmanager.svc.k3s.example.com:9093']

scrape_configs:
  - job_name: 'alertmanager'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'alertmanager.alertmanager.svc.k3s.example.com:9093'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kubernetes-apiservers'
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names: ['kube-system']
    scheme: https
    tls_config:
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_component]
        regex: apiserver
        action: keep

  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
      - role: node
    scheme: https
    tls_config:
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)

  - job_name: 'kubernetes-cadvisor'
    kubernetes_sd_configs:
      - role: node
    metrics_path: /metrics/cadvisor
    scheme: https
    tls_config:
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

  - job_name: 'kube-state-metrics'
    static_configs:
      - targets:
          - 'kube-state-metrics.kube-state-metrics.svc.k3s.example.com:8080'

  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        regex: "true"
        action: keep
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        regex: "([^:]+)(?::\\d+)?;(\\d+)"
        replacement: "$1:$2"
        target_label: __address__
        action: replace

  - job_name: 'node-exporter'
    static_configs:
      - targets:
          - 'node-exporter.node-exporter.svc.k3s.example.com:9100'
          - 'k3s-master-1.example.com:9100'
          - 'k3s-master-2.example.com:9100'
          - 'k3s-master-3.example.com:9100'
          - 'k3s-worker-1.example.com:9100'
          - 'k3s-worker-2.example.com:9100'
          - 'k3s-worker-3.example.com:9100'
          - 'longhorn-1.example.com:9100'
          - 'longhorn-2.example.com:9100'
          - 'longhorn-3.example.com:9100'
          - 'pihole-1.example.com:9100'
          - 'pihole-2.example.com:9100'
          - 'docker-host-1.example.com:9100'

  - job_name: 'proxmox'
    scrape_interval: 15s
    static_configs:
      - targets:
          - 'proxmox-node-1.example.com:9221'
          - 'proxmox-node-2.example.com:9221'
          - 'proxmox-node-3.example.com:9221'
    metrics_path: /pve

  - job_name: 'pihole'
    static_configs:
      - targets:
          - 'pihole-exporter.pihole-exporter.svc.k3s.example.com:9617'

  - job_name: 'longhorn-manager'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        action: keep
        regex: longhorn-system
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: longhorn-backend
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        action: keep
        regex: manager
    scrape_interval: 30s
    scrape_timeout: 10s

 
  - job_name: 'blackbox-exporter'
    static_configs:
      - targets: ['blackbox-exporter.blackbox.svc.k3s.example.com:9115']

  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_minimal]
    static_configs:
      - targets:
          - https://status.example.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter.blackbox.svc.k3s.example.com:9115

  - job_name: 'blackbox-icmp'
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
          - one.one.one.one
          - dns.google
          - status.example.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter.blackbox.svc.k3s.example.com:9115

  - job_name: 'blackbox-ssl'
    metrics_path: /probe
    params:
      module: [tls_connect]
    static_configs:
      - targets:
          - status.example.com:443
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter.blackbox.svc.k3s.example.com:9115
