apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: karma-config-pvc
  namespace: karma
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

