
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: affine-storage-pvc
  namespace: affine
spec:
  storageClassName: example-rbd-rbd
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
