apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - affine-config-pvc-persistentvolumeclaim.yml
  - affine-deployment.yml
  - affine-ingress.yml
  - affine-migration-job.yml
  - affine-namespace.yml
  - affine-postgres-service.yml
  - affine-postgres-statefulset.yml
  - affine-redis-deployment.yml
  - affine-redis-service.yml
  - affine-secrets.yml
  - affine-service.yml
  - affine-storage-pvc-persistentvolumeclaim.yml
