apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana-app-service.yml
  - grafana-data-pvc-persistentvolumeclaim.yml
  - grafana-deployment.yml
  - grafana-ingress.yml
  - grafana-namespace.yml
