apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: npm-letsencrypt-pvc
  namespace: nginx-proxy-manager
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
