apiVersion: v1
kind: Secret
metadata:
  name: pulse-env
  namespace: pulse
type: Opaque
stringData:
  PULSE_AUTH_USER: "REPLACE_ME"
  PULSE_AUTH_PASS: "REPLACE_ME"
  LOG_LEVEL: "REPLACE_ME"
  DISCOVERY_SUBNET: "REPLACE_ME"

