---
apiVersion: v1
kind: Namespace
metadata:
  name: alertmanager


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-config-pvc
  namespace: alertmanager
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-data-pvc
  namespace: alertmanager
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: alertmanager
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname','instance']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 9999h
      receiver: 'discord'

    receivers:
      - name: 'discord'
        discord_configs:
          - webhook_url: 'https://discord.com/api/webhooks/1387482313645887691/Qkty4ScCeb0jF6Xzo5MFMkt_xGbH8VCRTuJU_-gMJnkwvelGvLblPlhiJXN2lcQykUa9'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: alertmanager
  labels:
    app: alertmanager
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
      initContainers:
        - name: init-config
          image: busybox:1.37
          command:
            - sh
            - -c
            - |
              if [ ! -f /host-config/alertmanager.yml ]; then
                cp -r /tmp-config/. /host-config/
                chown -R 65534:65534 /host-config
              fi
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 50m
              memory: 64Mi
          volumeMounts:
            - name: config-cm
              mountPath: /tmp-config
            - name: config-host
              mountPath: /host-config
      containers:
        - name: alertmanager
          image: prom/alertmanager:v0.30.0
          imagePullPolicy: IfNotPresent
          args:
            - --config.file=/etc/alertmanager/alertmanager.yml
            - --storage.path=/data
          ports:
            - name: web
              containerPort: 9093
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: config-host
              mountPath: /etc/alertmanager
            - name: data
              mountPath: /data
      volumes:
        - name: config-cm
          configMap:
            name: alertmanager-config
        - name: config-host
          persistentVolumeClaim:
            claimName: alertmanager-config-pvc
        - name: data
          persistentVolumeClaim:
            claimName: alertmanager-data-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: alertmanager
spec:
  type: ClusterIP
  selector:
    app: alertmanager
  ports:
    - name: web
      port: 9093
      targetPort: 9093
