
# =====================================
# 1. Homepage Environment Secret
# =====================================
---
apiVersion: v1
kind: Secret
metadata:
  name: homepage-env
  namespace: homepage
type: Opaque
stringData:
  HOMEPAGE_VAR_PROXMOX_USERNAME: "REPLACE_ME"
  HOMEPAGE_VAR_PROXMOX_PASSWORD: "REPLACE_ME"
  HOMEPAGE_VAR_PIHOLE_01_KEY: "REPLACE_ME"
  HOMEPAGE_VAR_PIHOLE_02_KEY: "REPLACE_ME"
  HOMEPAGE_VAR_PIHOLE_03_KEY: "REPLACE_ME"
  HOMEPAGE_VAR_JELLYFIN_KEY: "REPLACE_ME"
  HOMEPAGE_VAR_SONARR_KEY: "REPLACE_ME"
  HOMEPAGE_VAR_RADARR_KEY: "REPLACE_ME"
  HOMEPAGE_VAR_QBITTORRENT_USERNAME: "REPLACE_ME"
  HOMEPAGE_VAR_QBITTORRENT_PASSWORD: "REPLACE_ME"
  HOMEPAGE_VAR_OMV_USERNAME: "REPLACE_ME"
  HOMEPAGE_VAR_OMV_PASSWORD: "REPLACE_ME"
  HOMEPAGE_VAR_AUTHENTIK_KEY: "REPLACE_ME"
  HOMEPAGE_VAR_PBS_USERNAME: "REPLACE_ME"
  HOMEPAGE_VAR_PBS_PASSWORD: "REPLACE_ME"
  HOMEPAGE_VAR_ZABBIX_KEY: "REPLACE_ME"
  HOMEPAGE_VAR_WIREGUARD_USERNAME: "REPLACE_ME"
  HOMEPAGE_VAR_WIREGUARD_PASSWORD: "REPLACE_ME"
