---
apiVersion: v1
kind: Secret
metadata:
  name: authentik-secrets
  namespace: authentik
type: Opaque
stringData:
  secret_key: "REPLACE_ME"
---
apiVersion: v1
kind: Secret
metadata:
  name: ak-ldap-outpost-secret
  namespace: authentik
type: Opaque
stringData:
  AUTHENTIK_HOST: "http://authentik-server-app"
  AUTHENTIK_INSECURE: "true"
  AUTHENTIK_TOKEN: "REPLACE_ME"
