apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homepage-config-pvc
  namespace: homepage
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

