services:
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:4.0.19
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /mnt/docker/sonarr/config/:/config
      - /mnt/docker/jellyfin/media/series:/tv
      - /mnt/docker/qbittorrent/downloads/:/downloads
    ports:
      - "8989:8989"
    networks:
      - media
    restart: unless-stopped

networks:
  media:
    external: true
    name: media
