apiVersion: v1
kind: Secret
metadata:
  name: pastefy-db-secret
  namespace: pastefy
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "REPLACE_ME"
  MYSQL_DATABASE: UkVQTEFDRV9NRQ==
  MYSQL_USER: "REPLACE_ME"
  MYSQL_PASSWORD: "REPLACE_ME"


