version: '3.8'
services:
  vaultwarden:
    image: vaultwarden/server:1.35.2
    environment:
      DATABASE_URL: ${VAULTWARDEN_DATABASE_URL}
    ports:
      - "80:80"
    volumes:
      - '/docker/vaultwarden/:/data'


  vaultwarden-db:
    image: postgres:18
    environment:
      POSTGRES_DB: ${VAULTWARDEN_POSTGRES_DB}
      POSTGRES_USER: ${VAULTWARDEN_POSTGRES_USER}
      POSTGRES_PASSWORD: ${VAULTWARDEN_POSTGRES_PASSWORD}
    volumes:
      - './postgres/:/var/lib/postgresql/data'
