services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2026.06.0
    restart: unless-stopped
    hostname: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
      - "4443:443/tcp"
    environment:
      TZ: "${TZ}"
      FTLCONF_dns_upstreams: "unbound#53"
      FTLCONF_dns_listeningMode: "ALL"
    volumes:
      - "/docker/pihole:/etc/pihole"
    networks:
      - pihole_network

  unbound:
    container_name: unbound
    image: klutchell/unbound:1.25.1
    restart: unless-stopped
    networks:
      - pihole_network

networks:
  pihole_network:
    driver: bridge
