apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speedtest-tracker-config
  namespace: speedtest-tracker
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
