apiVersion: v1
kind: Secret
metadata:
  name: speedtest-tracker-db-secret
  namespace: speedtest-tracker
  labels:
    app: speedtest-tracker-db
type: Opaque
stringData:
  POSTGRES_DB: "REPLACE_ME"
  POSTGRES_USER: "REPLACE_ME"
  POSTGRES_PASSWORD: "REPLACE_ME"
