apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: node-exporter
  labels:
    k8s-app: node-exporter
spec:
  clusterIP: None
  selector:
    k8s-app: node-exporter
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
