apiVersion: v1
kind: Secret
metadata:
  name: mend-renovate-env
  namespace: renovate
type: Opaque
stringData:
  MEND_RNV_LICENSE_KEY: "REPLACE_ME"
  MEND_RNV_ACCEPT_TOS: "REPLACE_ME"

  MEND_RNV_ENDPOINT: "REPLACE_ME"
  MEND_RNV_GITLAB_PAT: "REPLACE_ME"

  MEND_RNV_API_SERVER_SECRET: "REPLACE_ME"

  MEND_RNV_SERVER_PORT: "REPLACE_ME"

---
apiVersion: v1
kind: Secret
metadata:
  name: renovate-gitlab-env
  namespace: renovate
type: Opaque
stringData:
  RENOVATE_PLATFORM: "REPLACE_ME"
  RENOVATE_ENDPOINT: "REPLACE_ME"
  RENOVATE_TOKEN: "REPLACE_ME"
  RENOVATE_REPOSITORY_CACHE: "REPLACE_ME"

