# Secrets example for Vaultwarden
---
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-db-secret
  namespace: vaultwarden
  labels:
    app: vaultwarden-db
type: Opaque
data:
  POSTGRES_DB: UkVQTEFDRV9NRQ==
  POSTGRES_USER: UkVQTEFDRV9NRQ==
  POSTGRES_PASSWORD: UkVQTEFDRV9NRQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
  namespace: vaultwarden
  labels:
    app: vaultwarden
type: Opaque
data:
  DATABASE_URL: UkVQTEFDRV9NRQ==
