
# =====================================
# 2. Secret for PostgreSQL credentials
# =====================================
---
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-db-secret
  namespace: vaultwarden
  labels:
    app: vaultwarden-db
type: Opaque
data:
  POSTGRES_DB:        dmF1bHR3YXJkZW4=           # "vaultwarden"
  POSTGRES_USER:      dmF1bHR3YXJkZW4=           # "vaultwarden"
  POSTGRES_PASSWORD:  UkVQTEFDRV9NRQ==  # "REPLACE_ME"

# =====================================
# 6. Secret for Vaultwarden application
# =====================================
---
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
  namespace: vaultwarden
  labels:
    app: vaultwarden
type: Opaque
data:
  DATABASE_URL: UkVQTEFDRV9NRQ==
