apiVersion: v1
kind: Secret
metadata:
  name: zabbix-db-secret
  namespace: zabbix
type: Opaque
stringData:
  POSTGRES_DB:       "zabbix"
  POSTGRES_USER: "REPLACE_ME"
  POSTGRES_PASSWORD: "REPLACE_ME"

