services:
  guacamole:
    image: abesnier/guacamole
    user: root
    environment:
      - EXTENSIONS=${GUACAMOLE_EXTENSIONS}
    volumes:
      - /docker/guacamole:/config
      - ./filetransfer:/tmp/filetransfer
    ports:
      - "8080:8080"


