



---
apiVersion: v1
kind: Secret
metadata:
  name: speedtest-tracker-db-secret
  namespace: speedtest-tracker
  labels:
    app: speedtest-tracker-db
type: Opaque
data:
  POSTGRES_DB:       c3BlZWR0ZXN0X3RyYWNrZXI=
  POSTGRES_USER:     c3BlZWR0ZXN0LXRyYWNrZXI=
  POSTGRES_PASSWORD: UkVQTEFDRV9NRQ==
