name: Auto-Approve Renovate

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  pull-requests: write
  contents: write

jobs:
  approve-renovate:
    name: approve-renovate
    runs-on: ubuntu-latest
    if: github.actor == 'renovate[bot]'
    steps:
      - name: Approve PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr review ${{ github.event.pull_request.number }} --approve -R ${{ github.repository }}

      - name: Enable auto-merge (squash)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge ${{ github.event.pull_request.number }} --auto --squash -R ${{ github.repository }}
